# Generated by Django 3.0.5 on 2020-05-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='ChildStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childschedule',
            name='StartTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='Capacity',
            field=models.SmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='image',
            name='CreatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sickform',
            name='FormContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sickform',
            name='FormTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='CreateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='StoryContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='StartTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
