# Generated by Django 3.0.5 on 2020-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200528_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childschedule',
            name='StartTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='CreatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='CreateDate',
            field=models.DateTimeField(),
        ),
    ]
